[package]
name = "instument-pitch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pitch-detection = "0.2.0"
soundio = "0.2.1"